DROP TABLE IF EXISTS Contacts;

CREATE TABLE Contacts(
contact_id int UNSIGNED NOT NULL AUTO_INCREMENT ,
name VARCHAR( 100 ) NOT NULL ,
createdAt DATETIME NOT NULL ,
updatedAt DATETIME NOT NULL ,
PRIMARY KEY ( contact_id )
)
